/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDevRouteRouteImport } from './routes/_authenticated/dev/route'
import { Route as AuthenticatedDistrictRouteImport } from './routes/_authenticated/district'
import { Route as AuthenticatedEduRouteRouteImport } from './routes/_authenticated/edu/route'
import { Route as AuthenticatedFirmwareRouteImport } from './routes/_authenticated/firmware'
import { Route as AuthenticatedHangerRouteImport } from './routes/_authenticated/hanger'
import { Route as AuthenticatedJhaRouteImport } from './routes/_authenticated/jha'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedPortalsRouteImport } from './routes/_authenticated/portals'
import { Route as AuthenticatedSchedulingRouteImport } from './routes/_authenticated/scheduling'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSmsRouteImport } from './routes/_authenticated/sms'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as ClientTokenRouteImport } from './routes/client.$token'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdmin_lookupUuidRouteImport } from './routes/_authenticated/admin_lookup.$uuid'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedAnalyticsPersonalRouteImport } from './routes/_authenticated/analytics.personal'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev/index'
import { Route as AuthenticatedDroneUuidRouteImport } from './routes/_authenticated/drone/$uuid'
import { Route as AuthenticatedEduIndexRouteImport } from './routes/_authenticated/edu/index'
import { Route as AuthenticatedGearIndexRouteImport } from './routes/_authenticated/gear/index'
import { Route as AuthenticatedGearInventoryRouteImport } from './routes/_authenticated/gear/inventory'
import { Route as AuthenticatedGearLedgerRouteImport } from './routes/_authenticated/gear/ledger'
import { Route as AuthenticatedHangerIndexRouteImport } from './routes/_authenticated/hanger.index'
import { Route as AuthenticatedHangerPersonalRouteImport } from './routes/_authenticated/hanger.personal'
import { Route as AuthenticatedLedgerIndexRouteImport } from './routes/_authenticated/ledger.index'
import { Route as AuthenticatedLedgerPersonalRouteImport } from './routes/_authenticated/ledger.personal'
import { Route as AuthenticatedSquadronIndexRouteImport } from './routes/_authenticated/squadron/index'
import { Route as AuthenticatedSquadronSquadronIdRouteImport } from './routes/_authenticated/squadron/$squadronId'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedEduDistrictDistrictIdRouteImport } from './routes/_authenticated/edu/district.$districtId'
import { Route as AuthenticatedEduSchoolSchoolIdRouteImport } from './routes/_authenticated/edu/school.$schoolId'
import { Route as AuthenticatedEduStudentUserIdRouteImport } from './routes/_authenticated/edu/student.$userId'
import { Route as AuthenticatedGearTypeIndexRouteImport } from './routes/_authenticated/gear/$type.index'
import { Route as AuthenticatedGearTypeUuidRouteImport } from './routes/_authenticated/gear/$type.$uuid'
import { Route as AuthenticatedGearInventoryIndexRouteImport } from './routes/_authenticated/gear/inventory.index'
import { Route as AuthenticatedGearInventoryPersonalRouteImport } from './routes/_authenticated/gear/inventory.personal'
import { Route as AuthenticatedHangerTypeUuidRouteImport } from './routes/_authenticated/hanger/$type/$uuid'
import { Route as AuthenticatedHangerSquadronUuidRouteImport } from './routes/_authenticated/hanger.squadron.$uuid'
import { Route as AuthenticatedLedgerSquadronUuidRouteImport } from './routes/_authenticated/ledger.squadron.$uuid'
import { Route as AuthenticatedSquadronSquadronIdIndexRouteImport } from './routes/_authenticated/squadron/$squadronId.index'
import { Route as AuthenticatedSquadronSquadronIdAnalyticsRouteImport } from './routes/_authenticated/squadron/$squadronId.analytics'
import { Route as AuthenticatedSquadronSquadronIdInventoryRouteImport } from './routes/_authenticated/squadron/$squadronId.inventory'
import { Route as AuthenticatedSquadronSquadronIdSchedulerRouteImport } from './routes/_authenticated/squadron/$squadronId.scheduler'
import { Route as AuthenticatedSquadronManageUuidRouteImport } from './routes/_authenticated/squadron/manage.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRouteRoute = AuthenticatedDevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistrictRoute = AuthenticatedDistrictRouteImport.update({
  id: '/district',
  path: '/district',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEduRouteRoute = AuthenticatedEduRouteRouteImport.update({
  id: '/edu',
  path: '/edu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirmwareRoute = AuthenticatedFirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHangerRoute = AuthenticatedHangerRouteImport.update({
  id: '/hanger',
  path: '/hanger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJhaRoute = AuthenticatedJhaRouteImport.update({
  id: '/jha',
  path: '/jha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalsRoute = AuthenticatedPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulingRoute = AuthenticatedSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmsRoute = AuthenticatedSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClientTokenRoute = ClientTokenRouteImport.update({
  id: '/client/$token',
  path: '/client/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdmin_lookupUuidRoute =
  AuthenticatedAdmin_lookupUuidRouteImport.update({
    id: '/admin_lookup/$uuid',
    path: '/admin_lookup/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsPersonalRoute =
  AuthenticatedAnalyticsPersonalRouteImport.update({
    id: '/personal',
    path: '/personal',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDevRouteRoute,
} as any)
const AuthenticatedDroneUuidRoute = AuthenticatedDroneUuidRouteImport.update({
  id: '/drone/$uuid',
  path: '/drone/$uuid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEduIndexRoute = AuthenticatedEduIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedEduRouteRoute,
} as any)
const AuthenticatedGearIndexRoute = AuthenticatedGearIndexRouteImport.update({
  id: '/gear/',
  path: '/gear/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGearInventoryRoute =
  AuthenticatedGearInventoryRouteImport.update({
    id: '/gear/inventory',
    path: '/gear/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGearLedgerRoute = AuthenticatedGearLedgerRouteImport.update({
  id: '/gear/ledger',
  path: '/gear/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHangerIndexRoute =
  AuthenticatedHangerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHangerRoute,
  } as any)
const AuthenticatedHangerPersonalRoute =
  AuthenticatedHangerPersonalRouteImport.update({
    id: '/personal',
    path: '/personal',
    getParentRoute: () => AuthenticatedHangerRoute,
  } as any)
const AuthenticatedLedgerIndexRoute =
  AuthenticatedLedgerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLedgerRoute,
  } as any)
const AuthenticatedLedgerPersonalRoute =
  AuthenticatedLedgerPersonalRouteImport.update({
    id: '/personal',
    path: '/personal',
    getParentRoute: () => AuthenticatedLedgerRoute,
  } as any)
const AuthenticatedSquadronIndexRoute =
  AuthenticatedSquadronIndexRouteImport.update({
    id: '/squadron/',
    path: '/squadron/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSquadronSquadronIdRoute =
  AuthenticatedSquadronSquadronIdRouteImport.update({
    id: '/squadron/$squadronId',
    path: '/squadron/$squadronId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedEduDistrictDistrictIdRoute =
  AuthenticatedEduDistrictDistrictIdRouteImport.update({
    id: '/district/$districtId',
    path: '/district/$districtId',
    getParentRoute: () => AuthenticatedEduRouteRoute,
  } as any)
const AuthenticatedEduSchoolSchoolIdRoute =
  AuthenticatedEduSchoolSchoolIdRouteImport.update({
    id: '/school/$schoolId',
    path: '/school/$schoolId',
    getParentRoute: () => AuthenticatedEduRouteRoute,
  } as any)
const AuthenticatedEduStudentUserIdRoute =
  AuthenticatedEduStudentUserIdRouteImport.update({
    id: '/student/$userId',
    path: '/student/$userId',
    getParentRoute: () => AuthenticatedEduRouteRoute,
  } as any)
const AuthenticatedGearTypeIndexRoute =
  AuthenticatedGearTypeIndexRouteImport.update({
    id: '/gear/$type/',
    path: '/gear/$type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGearTypeUuidRoute =
  AuthenticatedGearTypeUuidRouteImport.update({
    id: '/gear/$type/$uuid',
    path: '/gear/$type/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGearInventoryIndexRoute =
  AuthenticatedGearInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGearInventoryRoute,
  } as any)
const AuthenticatedGearInventoryPersonalRoute =
  AuthenticatedGearInventoryPersonalRouteImport.update({
    id: '/personal',
    path: '/personal',
    getParentRoute: () => AuthenticatedGearInventoryRoute,
  } as any)
const AuthenticatedHangerTypeUuidRoute =
  AuthenticatedHangerTypeUuidRouteImport.update({
    id: '/$type/$uuid',
    path: '/$type/$uuid',
    getParentRoute: () => AuthenticatedHangerRoute,
  } as any)
const AuthenticatedHangerSquadronUuidRoute =
  AuthenticatedHangerSquadronUuidRouteImport.update({
    id: '/squadron/$uuid',
    path: '/squadron/$uuid',
    getParentRoute: () => AuthenticatedHangerRoute,
  } as any)
const AuthenticatedLedgerSquadronUuidRoute =
  AuthenticatedLedgerSquadronUuidRouteImport.update({
    id: '/squadron/$uuid',
    path: '/squadron/$uuid',
    getParentRoute: () => AuthenticatedLedgerRoute,
  } as any)
const AuthenticatedSquadronSquadronIdIndexRoute =
  AuthenticatedSquadronSquadronIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSquadronSquadronIdRoute,
  } as any)
const AuthenticatedSquadronSquadronIdAnalyticsRoute =
  AuthenticatedSquadronSquadronIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSquadronSquadronIdRoute,
  } as any)
const AuthenticatedSquadronSquadronIdInventoryRoute =
  AuthenticatedSquadronSquadronIdInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedSquadronSquadronIdRoute,
  } as any)
const AuthenticatedSquadronSquadronIdSchedulerRoute =
  AuthenticatedSquadronSquadronIdSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => AuthenticatedSquadronSquadronIdRoute,
  } as any)
const AuthenticatedSquadronManageUuidRoute =
  AuthenticatedSquadronManageUuidRouteImport.update({
    id: '/squadron/manage/$uuid',
    path: '/squadron/manage/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dev': typeof AuthenticatedDevRouteRouteWithChildren
  '/edu': typeof AuthenticatedEduRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/clients': typeof AuthenticatedClientsRoute
  '/district': typeof AuthenticatedDistrictRoute
  '/firmware': typeof AuthenticatedFirmwareRoute
  '/hanger': typeof AuthenticatedHangerRouteWithChildren
  '/jha': typeof AuthenticatedJhaRoute
  '/ledger': typeof AuthenticatedLedgerRouteWithChildren
  '/log': typeof AuthenticatedLogRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/client/$token': typeof ClientTokenRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/docs/': typeof DocsIndexRoute
  '/admin_lookup/$uuid': typeof AuthenticatedAdmin_lookupUuidRoute
  '/analytics/personal': typeof AuthenticatedAnalyticsPersonalRoute
  '/drone/$uuid': typeof AuthenticatedDroneUuidRoute
  '/gear/inventory': typeof AuthenticatedGearInventoryRouteWithChildren
  '/gear/ledger': typeof AuthenticatedGearLedgerRoute
  '/hanger/personal': typeof AuthenticatedHangerPersonalRoute
  '/ledger/personal': typeof AuthenticatedLedgerPersonalRoute
  '/squadron/$squadronId': typeof AuthenticatedSquadronSquadronIdRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
  '/edu/': typeof AuthenticatedEduIndexRoute
  '/gear/': typeof AuthenticatedGearIndexRoute
  '/hanger/': typeof AuthenticatedHangerIndexRoute
  '/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/squadron/': typeof AuthenticatedSquadronIndexRoute
  '/edu/district/$districtId': typeof AuthenticatedEduDistrictDistrictIdRoute
  '/edu/school/$schoolId': typeof AuthenticatedEduSchoolSchoolIdRoute
  '/edu/student/$userId': typeof AuthenticatedEduStudentUserIdRoute
  '/gear/$type/$uuid': typeof AuthenticatedGearTypeUuidRoute
  '/gear/inventory/personal': typeof AuthenticatedGearInventoryPersonalRoute
  '/hanger/$type/$uuid': typeof AuthenticatedHangerTypeUuidRoute
  '/hanger/squadron/$uuid': typeof AuthenticatedHangerSquadronUuidRoute
  '/ledger/squadron/$uuid': typeof AuthenticatedLedgerSquadronUuidRoute
  '/squadron/$squadronId/analytics': typeof AuthenticatedSquadronSquadronIdAnalyticsRoute
  '/squadron/$squadronId/inventory': typeof AuthenticatedSquadronSquadronIdInventoryRoute
  '/squadron/$squadronId/scheduler': typeof AuthenticatedSquadronSquadronIdSchedulerRoute
  '/squadron/manage/$uuid': typeof AuthenticatedSquadronManageUuidRoute
  '/gear/$type/': typeof AuthenticatedGearTypeIndexRoute
  '/gear/inventory/': typeof AuthenticatedGearInventoryIndexRoute
  '/squadron/$squadronId/': typeof AuthenticatedSquadronSquadronIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/district': typeof AuthenticatedDistrictRoute
  '/firmware': typeof AuthenticatedFirmwareRoute
  '/jha': typeof AuthenticatedJhaRoute
  '/log': typeof AuthenticatedLogRoute
  '/portals': typeof AuthenticatedPortalsRoute
  '/scheduling': typeof AuthenticatedSchedulingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/vault': typeof AuthenticatedVaultRoute
  '/client/$token': typeof ClientTokenRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/docs': typeof DocsIndexRoute
  '/admin_lookup/$uuid': typeof AuthenticatedAdmin_lookupUuidRoute
  '/analytics/personal': typeof AuthenticatedAnalyticsPersonalRoute
  '/drone/$uuid': typeof AuthenticatedDroneUuidRoute
  '/gear/ledger': typeof AuthenticatedGearLedgerRoute
  '/hanger/personal': typeof AuthenticatedHangerPersonalRoute
  '/ledger/personal': typeof AuthenticatedLedgerPersonalRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dev': typeof AuthenticatedDevIndexRoute
  '/edu': typeof AuthenticatedEduIndexRoute
  '/gear': typeof AuthenticatedGearIndexRoute
  '/hanger': typeof AuthenticatedHangerIndexRoute
  '/ledger': typeof AuthenticatedLedgerIndexRoute
  '/squadron': typeof AuthenticatedSquadronIndexRoute
  '/edu/district/$districtId': typeof AuthenticatedEduDistrictDistrictIdRoute
  '/edu/school/$schoolId': typeof AuthenticatedEduSchoolSchoolIdRoute
  '/edu/student/$userId': typeof AuthenticatedEduStudentUserIdRoute
  '/gear/$type/$uuid': typeof AuthenticatedGearTypeUuidRoute
  '/gear/inventory/personal': typeof AuthenticatedGearInventoryPersonalRoute
  '/hanger/$type/$uuid': typeof AuthenticatedHangerTypeUuidRoute
  '/hanger/squadron/$uuid': typeof AuthenticatedHangerSquadronUuidRoute
  '/ledger/squadron/$uuid': typeof AuthenticatedLedgerSquadronUuidRoute
  '/squadron/$squadronId/analytics': typeof AuthenticatedSquadronSquadronIdAnalyticsRoute
  '/squadron/$squadronId/inventory': typeof AuthenticatedSquadronSquadronIdInventoryRoute
  '/squadron/$squadronId/scheduler': typeof AuthenticatedSquadronSquadronIdSchedulerRoute
  '/squadron/manage/$uuid': typeof AuthenticatedSquadronManageUuidRoute
  '/gear/$type': typeof AuthenticatedGearTypeIndexRoute
  '/gear/inventory': typeof AuthenticatedGearInventoryIndexRoute
  '/squadron/$squadronId': typeof AuthenticatedSquadronSquadronIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dev': typeof AuthenticatedDevRouteRouteWithChildren
  '/_authenticated/edu': typeof AuthenticatedEduRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/district': typeof AuthenticatedDistrictRoute
  '/_authenticated/firmware': typeof AuthenticatedFirmwareRoute
  '/_authenticated/hanger': typeof AuthenticatedHangerRouteWithChildren
  '/_authenticated/jha': typeof AuthenticatedJhaRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRouteWithChildren
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/portals': typeof AuthenticatedPortalsRoute
  '/_authenticated/scheduling': typeof AuthenticatedSchedulingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sms': typeof AuthenticatedSmsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/client/$token': typeof ClientTokenRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/admin_lookup/$uuid': typeof AuthenticatedAdmin_lookupUuidRoute
  '/_authenticated/analytics/personal': typeof AuthenticatedAnalyticsPersonalRoute
  '/_authenticated/drone/$uuid': typeof AuthenticatedDroneUuidRoute
  '/_authenticated/gear/inventory': typeof AuthenticatedGearInventoryRouteWithChildren
  '/_authenticated/gear/ledger': typeof AuthenticatedGearLedgerRoute
  '/_authenticated/hanger/personal': typeof AuthenticatedHangerPersonalRoute
  '/_authenticated/ledger/personal': typeof AuthenticatedLedgerPersonalRoute
  '/_authenticated/squadron/$squadronId': typeof AuthenticatedSquadronSquadronIdRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
  '/_authenticated/edu/': typeof AuthenticatedEduIndexRoute
  '/_authenticated/gear/': typeof AuthenticatedGearIndexRoute
  '/_authenticated/hanger/': typeof AuthenticatedHangerIndexRoute
  '/_authenticated/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/_authenticated/squadron/': typeof AuthenticatedSquadronIndexRoute
  '/_authenticated/edu/district/$districtId': typeof AuthenticatedEduDistrictDistrictIdRoute
  '/_authenticated/edu/school/$schoolId': typeof AuthenticatedEduSchoolSchoolIdRoute
  '/_authenticated/edu/student/$userId': typeof AuthenticatedEduStudentUserIdRoute
  '/_authenticated/gear/$type/$uuid': typeof AuthenticatedGearTypeUuidRoute
  '/_authenticated/gear/inventory/personal': typeof AuthenticatedGearInventoryPersonalRoute
  '/_authenticated/hanger/$type/$uuid': typeof AuthenticatedHangerTypeUuidRoute
  '/_authenticated/hanger/squadron/$uuid': typeof AuthenticatedHangerSquadronUuidRoute
  '/_authenticated/ledger/squadron/$uuid': typeof AuthenticatedLedgerSquadronUuidRoute
  '/_authenticated/squadron/$squadronId/analytics': typeof AuthenticatedSquadronSquadronIdAnalyticsRoute
  '/_authenticated/squadron/$squadronId/inventory': typeof AuthenticatedSquadronSquadronIdInventoryRoute
  '/_authenticated/squadron/$squadronId/scheduler': typeof AuthenticatedSquadronSquadronIdSchedulerRoute
  '/_authenticated/squadron/manage/$uuid': typeof AuthenticatedSquadronManageUuidRoute
  '/_authenticated/gear/$type/': typeof AuthenticatedGearTypeIndexRoute
  '/_authenticated/gear/inventory/': typeof AuthenticatedGearInventoryIndexRoute
  '/_authenticated/squadron/$squadronId/': typeof AuthenticatedSquadronSquadronIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/update-password'
    | '/admin'
    | '/dev'
    | '/edu'
    | '/analytics'
    | '/clients'
    | '/district'
    | '/firmware'
    | '/hanger'
    | '/jha'
    | '/ledger'
    | '/log'
    | '/portals'
    | '/scheduling'
    | '/settings'
    | '/sms'
    | '/teams'
    | '/vault'
    | '/client/$token'
    | '/docs/$slug'
    | '/portal/$token'
    | '/docs/'
    | '/admin_lookup/$uuid'
    | '/analytics/personal'
    | '/drone/$uuid'
    | '/gear/inventory'
    | '/gear/ledger'
    | '/hanger/personal'
    | '/ledger/personal'
    | '/squadron/$squadronId'
    | '/teams/$teamId'
    | '/admin/'
    | '/analytics/'
    | '/dashboard/'
    | '/dev/'
    | '/edu/'
    | '/gear/'
    | '/hanger/'
    | '/ledger/'
    | '/squadron/'
    | '/edu/district/$districtId'
    | '/edu/school/$schoolId'
    | '/edu/student/$userId'
    | '/gear/$type/$uuid'
    | '/gear/inventory/personal'
    | '/hanger/$type/$uuid'
    | '/hanger/squadron/$uuid'
    | '/ledger/squadron/$uuid'
    | '/squadron/$squadronId/analytics'
    | '/squadron/$squadronId/inventory'
    | '/squadron/$squadronId/scheduler'
    | '/squadron/manage/$uuid'
    | '/gear/$type/'
    | '/gear/inventory/'
    | '/squadron/$squadronId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/update-password'
    | '/clients'
    | '/district'
    | '/firmware'
    | '/jha'
    | '/log'
    | '/portals'
    | '/scheduling'
    | '/settings'
    | '/sms'
    | '/teams'
    | '/vault'
    | '/client/$token'
    | '/docs/$slug'
    | '/portal/$token'
    | '/docs'
    | '/admin_lookup/$uuid'
    | '/analytics/personal'
    | '/drone/$uuid'
    | '/gear/ledger'
    | '/hanger/personal'
    | '/ledger/personal'
    | '/teams/$teamId'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/dev'
    | '/edu'
    | '/gear'
    | '/hanger'
    | '/ledger'
    | '/squadron'
    | '/edu/district/$districtId'
    | '/edu/school/$schoolId'
    | '/edu/student/$userId'
    | '/gear/$type/$uuid'
    | '/gear/inventory/personal'
    | '/hanger/$type/$uuid'
    | '/hanger/squadron/$uuid'
    | '/ledger/squadron/$uuid'
    | '/squadron/$squadronId/analytics'
    | '/squadron/$squadronId/inventory'
    | '/squadron/$squadronId/scheduler'
    | '/squadron/manage/$uuid'
    | '/gear/$type'
    | '/gear/inventory'
    | '/squadron/$squadronId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/update-password'
    | '/_authenticated/admin'
    | '/_authenticated/dev'
    | '/_authenticated/edu'
    | '/_authenticated/analytics'
    | '/_authenticated/clients'
    | '/_authenticated/district'
    | '/_authenticated/firmware'
    | '/_authenticated/hanger'
    | '/_authenticated/jha'
    | '/_authenticated/ledger'
    | '/_authenticated/log'
    | '/_authenticated/portals'
    | '/_authenticated/scheduling'
    | '/_authenticated/settings'
    | '/_authenticated/sms'
    | '/_authenticated/teams'
    | '/_authenticated/vault'
    | '/client/$token'
    | '/docs/$slug'
    | '/portal/$token'
    | '/docs/'
    | '/_authenticated/admin_lookup/$uuid'
    | '/_authenticated/analytics/personal'
    | '/_authenticated/drone/$uuid'
    | '/_authenticated/gear/inventory'
    | '/_authenticated/gear/ledger'
    | '/_authenticated/hanger/personal'
    | '/_authenticated/ledger/personal'
    | '/_authenticated/squadron/$squadronId'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/admin/'
    | '/_authenticated/analytics/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dev/'
    | '/_authenticated/edu/'
    | '/_authenticated/gear/'
    | '/_authenticated/hanger/'
    | '/_authenticated/ledger/'
    | '/_authenticated/squadron/'
    | '/_authenticated/edu/district/$districtId'
    | '/_authenticated/edu/school/$schoolId'
    | '/_authenticated/edu/student/$userId'
    | '/_authenticated/gear/$type/$uuid'
    | '/_authenticated/gear/inventory/personal'
    | '/_authenticated/hanger/$type/$uuid'
    | '/_authenticated/hanger/squadron/$uuid'
    | '/_authenticated/ledger/squadron/$uuid'
    | '/_authenticated/squadron/$squadronId/analytics'
    | '/_authenticated/squadron/$squadronId/inventory'
    | '/_authenticated/squadron/$squadronId/scheduler'
    | '/_authenticated/squadron/manage/$uuid'
    | '/_authenticated/gear/$type/'
    | '/_authenticated/gear/inventory/'
    | '/_authenticated/squadron/$squadronId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ClientTokenRoute: typeof ClientTokenRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/district': {
      id: '/_authenticated/district'
      path: '/district'
      fullPath: '/district'
      preLoaderRoute: typeof AuthenticatedDistrictRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edu': {
      id: '/_authenticated/edu'
      path: '/edu'
      fullPath: '/edu'
      preLoaderRoute: typeof AuthenticatedEduRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/firmware': {
      id: '/_authenticated/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof AuthenticatedFirmwareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hanger': {
      id: '/_authenticated/hanger'
      path: '/hanger'
      fullPath: '/hanger'
      preLoaderRoute: typeof AuthenticatedHangerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jha': {
      id: '/_authenticated/jha'
      path: '/jha'
      fullPath: '/jha'
      preLoaderRoute: typeof AuthenticatedJhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portals': {
      id: '/_authenticated/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof AuthenticatedPortalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling': {
      id: '/_authenticated/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof AuthenticatedSchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms': {
      id: '/_authenticated/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof AuthenticatedSmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/client/$token': {
      id: '/client/$token'
      path: '/client/$token'
      fullPath: '/client/$token'
      preLoaderRoute: typeof ClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin_lookup/$uuid': {
      id: '/_authenticated/admin_lookup/$uuid'
      path: '/admin_lookup/$uuid'
      fullPath: '/admin_lookup/$uuid'
      preLoaderRoute: typeof AuthenticatedAdmin_lookupUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/personal': {
      id: '/_authenticated/analytics/personal'
      path: '/personal'
      fullPath: '/analytics/personal'
      preLoaderRoute: typeof AuthenticatedAnalyticsPersonalRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedDevRouteRoute
    }
    '/_authenticated/drone/$uuid': {
      id: '/_authenticated/drone/$uuid'
      path: '/drone/$uuid'
      fullPath: '/drone/$uuid'
      preLoaderRoute: typeof AuthenticatedDroneUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edu/': {
      id: '/_authenticated/edu/'
      path: '/'
      fullPath: '/edu/'
      preLoaderRoute: typeof AuthenticatedEduIndexRouteImport
      parentRoute: typeof AuthenticatedEduRouteRoute
    }
    '/_authenticated/gear/': {
      id: '/_authenticated/gear/'
      path: '/gear'
      fullPath: '/gear/'
      preLoaderRoute: typeof AuthenticatedGearIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gear/inventory': {
      id: '/_authenticated/gear/inventory'
      path: '/gear/inventory'
      fullPath: '/gear/inventory'
      preLoaderRoute: typeof AuthenticatedGearInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gear/ledger': {
      id: '/_authenticated/gear/ledger'
      path: '/gear/ledger'
      fullPath: '/gear/ledger'
      preLoaderRoute: typeof AuthenticatedGearLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hanger/': {
      id: '/_authenticated/hanger/'
      path: '/'
      fullPath: '/hanger/'
      preLoaderRoute: typeof AuthenticatedHangerIndexRouteImport
      parentRoute: typeof AuthenticatedHangerRoute
    }
    '/_authenticated/hanger/personal': {
      id: '/_authenticated/hanger/personal'
      path: '/personal'
      fullPath: '/hanger/personal'
      preLoaderRoute: typeof AuthenticatedHangerPersonalRouteImport
      parentRoute: typeof AuthenticatedHangerRoute
    }
    '/_authenticated/ledger/': {
      id: '/_authenticated/ledger/'
      path: '/'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AuthenticatedLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedLedgerRoute
    }
    '/_authenticated/ledger/personal': {
      id: '/_authenticated/ledger/personal'
      path: '/personal'
      fullPath: '/ledger/personal'
      preLoaderRoute: typeof AuthenticatedLedgerPersonalRouteImport
      parentRoute: typeof AuthenticatedLedgerRoute
    }
    '/_authenticated/squadron/': {
      id: '/_authenticated/squadron/'
      path: '/squadron'
      fullPath: '/squadron/'
      preLoaderRoute: typeof AuthenticatedSquadronIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squadron/$squadronId': {
      id: '/_authenticated/squadron/$squadronId'
      path: '/squadron/$squadronId'
      fullPath: '/squadron/$squadronId'
      preLoaderRoute: typeof AuthenticatedSquadronSquadronIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/edu/district/$districtId': {
      id: '/_authenticated/edu/district/$districtId'
      path: '/district/$districtId'
      fullPath: '/edu/district/$districtId'
      preLoaderRoute: typeof AuthenticatedEduDistrictDistrictIdRouteImport
      parentRoute: typeof AuthenticatedEduRouteRoute
    }
    '/_authenticated/edu/school/$schoolId': {
      id: '/_authenticated/edu/school/$schoolId'
      path: '/school/$schoolId'
      fullPath: '/edu/school/$schoolId'
      preLoaderRoute: typeof AuthenticatedEduSchoolSchoolIdRouteImport
      parentRoute: typeof AuthenticatedEduRouteRoute
    }
    '/_authenticated/edu/student/$userId': {
      id: '/_authenticated/edu/student/$userId'
      path: '/student/$userId'
      fullPath: '/edu/student/$userId'
      preLoaderRoute: typeof AuthenticatedEduStudentUserIdRouteImport
      parentRoute: typeof AuthenticatedEduRouteRoute
    }
    '/_authenticated/gear/$type/': {
      id: '/_authenticated/gear/$type/'
      path: '/gear/$type'
      fullPath: '/gear/$type/'
      preLoaderRoute: typeof AuthenticatedGearTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gear/$type/$uuid': {
      id: '/_authenticated/gear/$type/$uuid'
      path: '/gear/$type/$uuid'
      fullPath: '/gear/$type/$uuid'
      preLoaderRoute: typeof AuthenticatedGearTypeUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gear/inventory/': {
      id: '/_authenticated/gear/inventory/'
      path: '/'
      fullPath: '/gear/inventory/'
      preLoaderRoute: typeof AuthenticatedGearInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedGearInventoryRoute
    }
    '/_authenticated/gear/inventory/personal': {
      id: '/_authenticated/gear/inventory/personal'
      path: '/personal'
      fullPath: '/gear/inventory/personal'
      preLoaderRoute: typeof AuthenticatedGearInventoryPersonalRouteImport
      parentRoute: typeof AuthenticatedGearInventoryRoute
    }
    '/_authenticated/hanger/$type/$uuid': {
      id: '/_authenticated/hanger/$type/$uuid'
      path: '/$type/$uuid'
      fullPath: '/hanger/$type/$uuid'
      preLoaderRoute: typeof AuthenticatedHangerTypeUuidRouteImport
      parentRoute: typeof AuthenticatedHangerRoute
    }
    '/_authenticated/hanger/squadron/$uuid': {
      id: '/_authenticated/hanger/squadron/$uuid'
      path: '/squadron/$uuid'
      fullPath: '/hanger/squadron/$uuid'
      preLoaderRoute: typeof AuthenticatedHangerSquadronUuidRouteImport
      parentRoute: typeof AuthenticatedHangerRoute
    }
    '/_authenticated/ledger/squadron/$uuid': {
      id: '/_authenticated/ledger/squadron/$uuid'
      path: '/squadron/$uuid'
      fullPath: '/ledger/squadron/$uuid'
      preLoaderRoute: typeof AuthenticatedLedgerSquadronUuidRouteImport
      parentRoute: typeof AuthenticatedLedgerRoute
    }
    '/_authenticated/squadron/$squadronId/': {
      id: '/_authenticated/squadron/$squadronId/'
      path: '/'
      fullPath: '/squadron/$squadronId/'
      preLoaderRoute: typeof AuthenticatedSquadronSquadronIdIndexRouteImport
      parentRoute: typeof AuthenticatedSquadronSquadronIdRoute
    }
    '/_authenticated/squadron/$squadronId/analytics': {
      id: '/_authenticated/squadron/$squadronId/analytics'
      path: '/analytics'
      fullPath: '/squadron/$squadronId/analytics'
      preLoaderRoute: typeof AuthenticatedSquadronSquadronIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSquadronSquadronIdRoute
    }
    '/_authenticated/squadron/$squadronId/inventory': {
      id: '/_authenticated/squadron/$squadronId/inventory'
      path: '/inventory'
      fullPath: '/squadron/$squadronId/inventory'
      preLoaderRoute: typeof AuthenticatedSquadronSquadronIdInventoryRouteImport
      parentRoute: typeof AuthenticatedSquadronSquadronIdRoute
    }
    '/_authenticated/squadron/$squadronId/scheduler': {
      id: '/_authenticated/squadron/$squadronId/scheduler'
      path: '/scheduler'
      fullPath: '/squadron/$squadronId/scheduler'
      preLoaderRoute: typeof AuthenticatedSquadronSquadronIdSchedulerRouteImport
      parentRoute: typeof AuthenticatedSquadronSquadronIdRoute
    }
    '/_authenticated/squadron/manage/$uuid': {
      id: '/_authenticated/squadron/manage/$uuid'
      path: '/squadron/manage/$uuid'
      fullPath: '/squadron/manage/$uuid'
      preLoaderRoute: typeof AuthenticatedSquadronManageUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDevRouteRouteChildren {
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedDevRouteRouteChildren: AuthenticatedDevRouteRouteChildren = {
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedDevRouteRouteWithChildren =
  AuthenticatedDevRouteRoute._addFileChildren(
    AuthenticatedDevRouteRouteChildren,
  )

interface AuthenticatedEduRouteRouteChildren {
  AuthenticatedEduIndexRoute: typeof AuthenticatedEduIndexRoute
  AuthenticatedEduDistrictDistrictIdRoute: typeof AuthenticatedEduDistrictDistrictIdRoute
  AuthenticatedEduSchoolSchoolIdRoute: typeof AuthenticatedEduSchoolSchoolIdRoute
  AuthenticatedEduStudentUserIdRoute: typeof AuthenticatedEduStudentUserIdRoute
}

const AuthenticatedEduRouteRouteChildren: AuthenticatedEduRouteRouteChildren = {
  AuthenticatedEduIndexRoute: AuthenticatedEduIndexRoute,
  AuthenticatedEduDistrictDistrictIdRoute:
    AuthenticatedEduDistrictDistrictIdRoute,
  AuthenticatedEduSchoolSchoolIdRoute: AuthenticatedEduSchoolSchoolIdRoute,
  AuthenticatedEduStudentUserIdRoute: AuthenticatedEduStudentUserIdRoute,
}

const AuthenticatedEduRouteRouteWithChildren =
  AuthenticatedEduRouteRoute._addFileChildren(
    AuthenticatedEduRouteRouteChildren,
  )

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsPersonalRoute: typeof AuthenticatedAnalyticsPersonalRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsPersonalRoute: AuthenticatedAnalyticsPersonalRoute,
    AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedHangerRouteChildren {
  AuthenticatedHangerPersonalRoute: typeof AuthenticatedHangerPersonalRoute
  AuthenticatedHangerIndexRoute: typeof AuthenticatedHangerIndexRoute
  AuthenticatedHangerTypeUuidRoute: typeof AuthenticatedHangerTypeUuidRoute
  AuthenticatedHangerSquadronUuidRoute: typeof AuthenticatedHangerSquadronUuidRoute
}

const AuthenticatedHangerRouteChildren: AuthenticatedHangerRouteChildren = {
  AuthenticatedHangerPersonalRoute: AuthenticatedHangerPersonalRoute,
  AuthenticatedHangerIndexRoute: AuthenticatedHangerIndexRoute,
  AuthenticatedHangerTypeUuidRoute: AuthenticatedHangerTypeUuidRoute,
  AuthenticatedHangerSquadronUuidRoute: AuthenticatedHangerSquadronUuidRoute,
}

const AuthenticatedHangerRouteWithChildren =
  AuthenticatedHangerRoute._addFileChildren(AuthenticatedHangerRouteChildren)

interface AuthenticatedLedgerRouteChildren {
  AuthenticatedLedgerPersonalRoute: typeof AuthenticatedLedgerPersonalRoute
  AuthenticatedLedgerIndexRoute: typeof AuthenticatedLedgerIndexRoute
  AuthenticatedLedgerSquadronUuidRoute: typeof AuthenticatedLedgerSquadronUuidRoute
}

const AuthenticatedLedgerRouteChildren: AuthenticatedLedgerRouteChildren = {
  AuthenticatedLedgerPersonalRoute: AuthenticatedLedgerPersonalRoute,
  AuthenticatedLedgerIndexRoute: AuthenticatedLedgerIndexRoute,
  AuthenticatedLedgerSquadronUuidRoute: AuthenticatedLedgerSquadronUuidRoute,
}

const AuthenticatedLedgerRouteWithChildren =
  AuthenticatedLedgerRoute._addFileChildren(AuthenticatedLedgerRouteChildren)

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedGearInventoryRouteChildren {
  AuthenticatedGearInventoryPersonalRoute: typeof AuthenticatedGearInventoryPersonalRoute
  AuthenticatedGearInventoryIndexRoute: typeof AuthenticatedGearInventoryIndexRoute
}

const AuthenticatedGearInventoryRouteChildren: AuthenticatedGearInventoryRouteChildren =
  {
    AuthenticatedGearInventoryPersonalRoute:
      AuthenticatedGearInventoryPersonalRoute,
    AuthenticatedGearInventoryIndexRoute: AuthenticatedGearInventoryIndexRoute,
  }

const AuthenticatedGearInventoryRouteWithChildren =
  AuthenticatedGearInventoryRoute._addFileChildren(
    AuthenticatedGearInventoryRouteChildren,
  )

interface AuthenticatedSquadronSquadronIdRouteChildren {
  AuthenticatedSquadronSquadronIdAnalyticsRoute: typeof AuthenticatedSquadronSquadronIdAnalyticsRoute
  AuthenticatedSquadronSquadronIdInventoryRoute: typeof AuthenticatedSquadronSquadronIdInventoryRoute
  AuthenticatedSquadronSquadronIdSchedulerRoute: typeof AuthenticatedSquadronSquadronIdSchedulerRoute
  AuthenticatedSquadronSquadronIdIndexRoute: typeof AuthenticatedSquadronSquadronIdIndexRoute
}

const AuthenticatedSquadronSquadronIdRouteChildren: AuthenticatedSquadronSquadronIdRouteChildren =
  {
    AuthenticatedSquadronSquadronIdAnalyticsRoute:
      AuthenticatedSquadronSquadronIdAnalyticsRoute,
    AuthenticatedSquadronSquadronIdInventoryRoute:
      AuthenticatedSquadronSquadronIdInventoryRoute,
    AuthenticatedSquadronSquadronIdSchedulerRoute:
      AuthenticatedSquadronSquadronIdSchedulerRoute,
    AuthenticatedSquadronSquadronIdIndexRoute:
      AuthenticatedSquadronSquadronIdIndexRoute,
  }

const AuthenticatedSquadronSquadronIdRouteWithChildren =
  AuthenticatedSquadronSquadronIdRoute._addFileChildren(
    AuthenticatedSquadronSquadronIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDevRouteRoute: typeof AuthenticatedDevRouteRouteWithChildren
  AuthenticatedEduRouteRoute: typeof AuthenticatedEduRouteRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDistrictRoute: typeof AuthenticatedDistrictRoute
  AuthenticatedFirmwareRoute: typeof AuthenticatedFirmwareRoute
  AuthenticatedHangerRoute: typeof AuthenticatedHangerRouteWithChildren
  AuthenticatedJhaRoute: typeof AuthenticatedJhaRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRouteWithChildren
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedPortalsRoute: typeof AuthenticatedPortalsRoute
  AuthenticatedSchedulingRoute: typeof AuthenticatedSchedulingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSmsRoute: typeof AuthenticatedSmsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedAdmin_lookupUuidRoute: typeof AuthenticatedAdmin_lookupUuidRoute
  AuthenticatedDroneUuidRoute: typeof AuthenticatedDroneUuidRoute
  AuthenticatedGearInventoryRoute: typeof AuthenticatedGearInventoryRouteWithChildren
  AuthenticatedGearLedgerRoute: typeof AuthenticatedGearLedgerRoute
  AuthenticatedSquadronSquadronIdRoute: typeof AuthenticatedSquadronSquadronIdRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedGearIndexRoute: typeof AuthenticatedGearIndexRoute
  AuthenticatedSquadronIndexRoute: typeof AuthenticatedSquadronIndexRoute
  AuthenticatedGearTypeUuidRoute: typeof AuthenticatedGearTypeUuidRoute
  AuthenticatedSquadronManageUuidRoute: typeof AuthenticatedSquadronManageUuidRoute
  AuthenticatedGearTypeIndexRoute: typeof AuthenticatedGearTypeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDevRouteRoute: AuthenticatedDevRouteRouteWithChildren,
  AuthenticatedEduRouteRoute: AuthenticatedEduRouteRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDistrictRoute: AuthenticatedDistrictRoute,
  AuthenticatedFirmwareRoute: AuthenticatedFirmwareRoute,
  AuthenticatedHangerRoute: AuthenticatedHangerRouteWithChildren,
  AuthenticatedJhaRoute: AuthenticatedJhaRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRouteWithChildren,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedPortalsRoute: AuthenticatedPortalsRoute,
  AuthenticatedSchedulingRoute: AuthenticatedSchedulingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSmsRoute: AuthenticatedSmsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedAdmin_lookupUuidRoute: AuthenticatedAdmin_lookupUuidRoute,
  AuthenticatedDroneUuidRoute: AuthenticatedDroneUuidRoute,
  AuthenticatedGearInventoryRoute: AuthenticatedGearInventoryRouteWithChildren,
  AuthenticatedGearLedgerRoute: AuthenticatedGearLedgerRoute,
  AuthenticatedSquadronSquadronIdRoute:
    AuthenticatedSquadronSquadronIdRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedGearIndexRoute: AuthenticatedGearIndexRoute,
  AuthenticatedSquadronIndexRoute: AuthenticatedSquadronIndexRoute,
  AuthenticatedGearTypeUuidRoute: AuthenticatedGearTypeUuidRoute,
  AuthenticatedSquadronManageUuidRoute: AuthenticatedSquadronManageUuidRoute,
  AuthenticatedGearTypeIndexRoute: AuthenticatedGearTypeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ClientTokenRoute: ClientTokenRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
