/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedHangerRouteImport } from './routes/_authenticated/hanger'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdmin_lookupUuidRouteImport } from './routes/_authenticated/admin_lookup.$uuid'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDroneUuidRouteImport } from './routes/_authenticated/drone/$uuid'
import { Route as AuthenticatedSquadronIndexRouteImport } from './routes/_authenticated/squadron/index'
import { Route as AuthenticatedSquadronSquadronIdRouteImport } from './routes/_authenticated/squadron/$squadronId'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedHangerTypeUuidRouteImport } from './routes/_authenticated/hanger/$type/$uuid'
import { Route as AuthenticatedSquadronManageUuidRouteImport } from './routes/_authenticated/squadron/manage.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHangerRoute = AuthenticatedHangerRouteImport.update({
  id: '/hanger',
  path: '/hanger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdmin_lookupUuidRoute =
  AuthenticatedAdmin_lookupUuidRouteImport.update({
    id: '/admin_lookup/$uuid',
    path: '/admin_lookup/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDroneUuidRoute = AuthenticatedDroneUuidRouteImport.update({
  id: '/drone/$uuid',
  path: '/drone/$uuid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadronIndexRoute =
  AuthenticatedSquadronIndexRouteImport.update({
    id: '/squadron/',
    path: '/squadron/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSquadronSquadronIdRoute =
  AuthenticatedSquadronSquadronIdRouteImport.update({
    id: '/squadron/$squadronId',
    path: '/squadron/$squadronId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedHangerTypeUuidRoute =
  AuthenticatedHangerTypeUuidRouteImport.update({
    id: '/$type/$uuid',
    path: '/$type/$uuid',
    getParentRoute: () => AuthenticatedHangerRoute,
  } as any)
const AuthenticatedSquadronManageUuidRoute =
  AuthenticatedSquadronManageUuidRouteImport.update({
    id: '/squadron/manage/$uuid',
    path: '/squadron/manage/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/hanger': typeof AuthenticatedHangerRouteWithChildren
  '/log': typeof AuthenticatedLogRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/admin_lookup/$uuid': typeof AuthenticatedAdmin_lookupUuidRoute
  '/drone/$uuid': typeof AuthenticatedDroneUuidRoute
  '/squadron/$squadronId': typeof AuthenticatedSquadronSquadronIdRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/squadron/': typeof AuthenticatedSquadronIndexRoute
  '/hanger/$type/$uuid': typeof AuthenticatedHangerTypeUuidRoute
  '/squadron/manage/$uuid': typeof AuthenticatedSquadronManageUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/hanger': typeof AuthenticatedHangerRouteWithChildren
  '/log': typeof AuthenticatedLogRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/admin_lookup/$uuid': typeof AuthenticatedAdmin_lookupUuidRoute
  '/drone/$uuid': typeof AuthenticatedDroneUuidRoute
  '/squadron/$squadronId': typeof AuthenticatedSquadronSquadronIdRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/squadron': typeof AuthenticatedSquadronIndexRoute
  '/hanger/$type/$uuid': typeof AuthenticatedHangerTypeUuidRoute
  '/squadron/manage/$uuid': typeof AuthenticatedSquadronManageUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/hanger': typeof AuthenticatedHangerRouteWithChildren
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/_authenticated/admin_lookup/$uuid': typeof AuthenticatedAdmin_lookupUuidRoute
  '/_authenticated/drone/$uuid': typeof AuthenticatedDroneUuidRoute
  '/_authenticated/squadron/$squadronId': typeof AuthenticatedSquadronSquadronIdRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/squadron/': typeof AuthenticatedSquadronIndexRoute
  '/_authenticated/hanger/$type/$uuid': typeof AuthenticatedHangerTypeUuidRoute
  '/_authenticated/squadron/manage/$uuid': typeof AuthenticatedSquadronManageUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/hanger'
    | '/log'
    | '/settings'
    | '/teams'
    | '/admin_lookup/$uuid'
    | '/drone/$uuid'
    | '/squadron/$squadronId'
    | '/teams/$teamId'
    | '/admin/'
    | '/dashboard/'
    | '/squadron/'
    | '/hanger/$type/$uuid'
    | '/squadron/manage/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/hanger'
    | '/log'
    | '/settings'
    | '/teams'
    | '/admin_lookup/$uuid'
    | '/drone/$uuid'
    | '/squadron/$squadronId'
    | '/teams/$teamId'
    | '/admin'
    | '/dashboard'
    | '/squadron'
    | '/hanger/$type/$uuid'
    | '/squadron/manage/$uuid'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/hanger'
    | '/_authenticated/log'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/_authenticated/admin_lookup/$uuid'
    | '/_authenticated/drone/$uuid'
    | '/_authenticated/squadron/$squadronId'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/squadron/'
    | '/_authenticated/hanger/$type/$uuid'
    | '/_authenticated/squadron/manage/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hanger': {
      id: '/_authenticated/hanger'
      path: '/hanger'
      fullPath: '/hanger'
      preLoaderRoute: typeof AuthenticatedHangerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin_lookup/$uuid': {
      id: '/_authenticated/admin_lookup/$uuid'
      path: '/admin_lookup/$uuid'
      fullPath: '/admin_lookup/$uuid'
      preLoaderRoute: typeof AuthenticatedAdmin_lookupUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drone/$uuid': {
      id: '/_authenticated/drone/$uuid'
      path: '/drone/$uuid'
      fullPath: '/drone/$uuid'
      preLoaderRoute: typeof AuthenticatedDroneUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squadron/': {
      id: '/_authenticated/squadron/'
      path: '/squadron'
      fullPath: '/squadron/'
      preLoaderRoute: typeof AuthenticatedSquadronIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squadron/$squadronId': {
      id: '/_authenticated/squadron/$squadronId'
      path: '/squadron/$squadronId'
      fullPath: '/squadron/$squadronId'
      preLoaderRoute: typeof AuthenticatedSquadronSquadronIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/hanger/$type/$uuid': {
      id: '/_authenticated/hanger/$type/$uuid'
      path: '/$type/$uuid'
      fullPath: '/hanger/$type/$uuid'
      preLoaderRoute: typeof AuthenticatedHangerTypeUuidRouteImport
      parentRoute: typeof AuthenticatedHangerRoute
    }
    '/_authenticated/squadron/manage/$uuid': {
      id: '/_authenticated/squadron/manage/$uuid'
      path: '/squadron/manage/$uuid'
      fullPath: '/squadron/manage/$uuid'
      preLoaderRoute: typeof AuthenticatedSquadronManageUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedHangerRouteChildren {
  AuthenticatedHangerTypeUuidRoute: typeof AuthenticatedHangerTypeUuidRoute
}

const AuthenticatedHangerRouteChildren: AuthenticatedHangerRouteChildren = {
  AuthenticatedHangerTypeUuidRoute: AuthenticatedHangerTypeUuidRoute,
}

const AuthenticatedHangerRouteWithChildren =
  AuthenticatedHangerRoute._addFileChildren(AuthenticatedHangerRouteChildren)

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedHangerRoute: typeof AuthenticatedHangerRouteWithChildren
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedAdmin_lookupUuidRoute: typeof AuthenticatedAdmin_lookupUuidRoute
  AuthenticatedDroneUuidRoute: typeof AuthenticatedDroneUuidRoute
  AuthenticatedSquadronSquadronIdRoute: typeof AuthenticatedSquadronSquadronIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedSquadronIndexRoute: typeof AuthenticatedSquadronIndexRoute
  AuthenticatedSquadronManageUuidRoute: typeof AuthenticatedSquadronManageUuidRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedHangerRoute: AuthenticatedHangerRouteWithChildren,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedAdmin_lookupUuidRoute: AuthenticatedAdmin_lookupUuidRoute,
  AuthenticatedDroneUuidRoute: AuthenticatedDroneUuidRoute,
  AuthenticatedSquadronSquadronIdRoute: AuthenticatedSquadronSquadronIdRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedSquadronIndexRoute: AuthenticatedSquadronIndexRoute,
  AuthenticatedSquadronManageUuidRoute: AuthenticatedSquadronManageUuidRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
